import {
  Accessibility,
  BotMessageSquare,
  Boxes,
  BrainCircuit,
  Braces,
  Blocks,
  ClipboardList,
  CodeXml,
  Component,
  Container,
  Cpu,
  Cylinder,
  Database,
  DatabaseZap,
  FileText,
  FlaskConical,
  Funnel,
  Gauge,
  Globe,
  Layers3,
  Leaf,
  Library,
  ListChecks,
  MousePointerClick,
  Network,
  Palette,
  Router,
  Search,
  Server,
  ShoppingCart,
  Smartphone,
  SquareStack,
  Table2,
  Target,
  Terminal,
  Triangle,
  Waves,
  Workflow,
  Zap,
} from "lucide-react";

const trackIcons = {
  all: Library,
  "interview-prep": FileText,
  backend: Server,
  databases: Database,
  nodejs: Terminal,
  nestjs: SquareStack,
  javascript: Braces,
  browser: Globe,
  react: Component,
  nextjs: Triangle,
  "ai-engineering": BrainCircuit,
  "system-design": Workflow,
  networking: Network,
  devops: Container,
  dotnet: Blocks,
  python: Terminal,
  "react-native": Smartphone,
  "frontend-architecture": Layers3,
};

const topicIcons = {
  "senior-full-stack-saas-job-prep": FileText,
  "senior-frontend-ecommerce-graphql": ShoppingCart,
  backend: Server,
  "senior-api-database-performance": Zap,
  "database-fundamentals": Database,
  "sql-fundamentals": Table2,
  "sql-query-optimization": Gauge,
  "sql-practice": ListChecks,
  "postgresql-fundamentals": Cylinder,
  "postgresql-performance": DatabaseZap,
  "mongodb-fundamentals": Leaf,
  "mongodb-aggregation": Funnel,
  "mongodb-indexing-performance": Gauge,
  "mongodb-advanced": Network,
  "nodejs-backend": Terminal,
  "nodejs-event-loop-runtime": Router,
  "nodejs-streams-buffers": Waves,
  "nestjs-fundamentals": Boxes,
  "nestjs-dependency-injection": Blocks,
  "nestjs-request-lifecycle": Workflow,
  "nestjs-data-persistence": Database,
  "nestjs-auth-microservices": Network,
  "express-framework": Router,
  "nestjs-queues-realtime": Workflow,
  javascript: Braces,
  "javascript-modules-import-export": CodeXml,
  "javascript-promises-async": Workflow,
  "javascript-event-loop-runtime": Router,
  "javascript-this-functions": Braces,
  "javascript-prototypes-objects": Blocks,
  "javascript-collections-iteration": Library,
  "javascript-loops-array-methods": Workflow,
  "javascript-scope-hoisting-closures": Layers3,
  "javascript-types-equality-copying": CodeXml,
  "javascript-execution-context": Layers3,
  "javascript-code-practice": ListChecks,
  "javascript-performance-debugging": Gauge,
  "browser-page-load-rendering": Globe,
  "css-fundamentals-layout": Palette,
  "dom-events-browser-apis": MousePointerClick,
  "frontend-react-next": Component,
  "typescript-react-architecture": Braces,
  "react-performance": Zap,
  "react-bundle-optimization": Zap,
  "react-core-through-17": Component,
  "react-internals-fiber": Cpu,
  "react-18-features": Workflow,
  "react-19-features": Component,
  "react-compiler": Zap,
  "react-data-fetching-state": Database,
  "react-forms-validation": ClipboardList,
  "react-testing": FlaskConical,
  "react-accessibility": Accessibility,
  "senior-frontend-react-scenarios": Workflow,
  "react-senior-drills": Target,
  "machine-coding": CodeXml,
  "nextjs-fundamentals": Triangle,
  "nextjs-rendering-caching": Layers3,
  "nextjs-routing-navigation": Router,
  "nextjs-server-client-components": Component,
  "nextjs-data-forms-mutations": Workflow,
  "nextjs-error-handling": FileText,
  "nextjs-metadata-seo": Search,
  "nextjs-security-auth": Blocks,
  "nextjs-proxy-observability": Network,
  "nextjs-styling-assets": Palette,
  "nextjs-deployment-production": Container,
  "nextjs-testing-tooling": ListChecks,
  "nextjs-optimizations": Gauge,
  "ai-frontend-engineering": BotMessageSquare,
  "system-design-microservices": Workflow,
  "kafka-event-streaming": Workflow,
  "rabbitmq-message-broker": Workflow,
  "mqtt-iot-messaging": Router,
  "nodejs-microservices-case-study": Boxes,
  "design-patterns": Blocks,
  "devops-docker-kubernetes": Container,
  "aws-saas-observability": Workflow,
  "networking-fundamentals": Network,
  "http-tls-protocols": Globe,
  "api-protocols": Workflow,
  "nginx-web-infrastructure": Router,
  "dotnet-csharp": Blocks,
  "python-backend-frameworks": Terminal,
  "mobile-react-native": Smartphone,
  "react-native-fundamentals": Smartphone,
  "react-native-networking-auth": Network,
  "react-native-performance": Gauge,
  "react-native-architecture": Layers3,
  "react-native-production": Container,
  "react-native-deep-linking-notifications": Router,
  "react-native-builds-releases": Boxes,
  "react-native-senior-scenarios": Workflow,
  "frontend-architecture-micro-frontends": Layers3,
  "frontend-system-design": Workflow,
};

export function TrackIcon({ slug }: { slug: string }) {
  const Icon = trackIcons[slug as keyof typeof trackIcons] ?? Library;

  return (
    <span className="topic-icon">
      <Icon size={18} />
    </span>
  );
}

export function TopicIcon({
  className,
  size = 17,
  slug,
}: {
  className?: string;
  size?: number;
  slug: string;
}) {
  const Icon = topicIcons[slug as keyof typeof topicIcons] ?? Library;

  return (
    <span className={className ? `topic-icon ${className}` : "topic-icon"}>
      <Icon size={size} />
    </span>
  );
}
